# Generated by Django 5.0.2 on 2024-03-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_student_course_student_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="id_number",
        ),
    ]
