# Generated by Django 5.0.2 on 2024-03-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsAndEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("summary", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "posted_as",
                    models.CharField(
                        choices=[("News", "News"), ("Event", "Event")], max_length=10
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("upload_time", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session", models.CharField(max_length=200, unique=True)),
                (
                    "is_current_session",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("next_session_begins", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
