# Generated by Django 5.0.2 on 2024-03-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsandevents",
            name="posted_as",
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="news/"),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="links",
            field=models.URLField(blank=True, null=True),
        ),
    ]
