# Generated by Django 5.0.2 on 2024-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_newsandevents_posted_as_newsandevents_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsandevents",
            name="image",
            field=models.ImageField(
                blank=True, default="default.png", null=True, upload_to="news/"
            ),
        ),
    ]
