# Generated by Django 5.0.2 on 2024-03-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="draft",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="pass_mark",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="timestamp",
        ),
        migrations.AlterField(
            model_name="quiz",
            name="category",
            field=models.TextField(
                blank=True,
                choices=[
                    ("assignment", "Assignment"),
                    ("practice_quiz", "Practice Quiz"),
                    ("exam", "Exam"),
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Sitting",
        ),
    ]
