# Generated by Django 5.0.2 on 2024-03-13 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_remove_sitting_course_remove_sitting_quiz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.quiz",
                verbose_name="Quiz",
            ),
            preserve_default=False,
        ),
    ]
