# Generated by Django 5.0.2 on 2024-03-13 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_alter_module_title"),
        ("quiz", "0005_question_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.question",
                verbose_name="Question",
            ),
        ),
        migrations.RemoveField(
            model_name="progress",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="choice",
            options={},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={},
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="correct",
        ),
        migrations.RemoveField(
            model_name="question",
            name="content",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation",
        ),
        migrations.RemoveField(
            model_name="question",
            name="figure",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="answers_at_end",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="category",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="description",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="draft",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="exam_paper",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="pass_mark",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="random_order",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="single_attempt",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="choice",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="Is Correct"),
        ),
        migrations.AddField(
            model_name="choice",
            name="text",
            field=models.CharField(default=1, max_length=1000, verbose_name="Choice"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="mark",
            field=models.IntegerField(default=1, verbose_name="Mark"),
        ),
        migrations.AddField(
            model_name="question",
            name="text",
            field=models.CharField(default=1, max_length=1000, verbose_name="Question"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="module",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.module",
            ),
        ),
        migrations.DeleteModel(
            name="MCQuestion",
        ),
        migrations.DeleteModel(
            name="Progress",
        ),
    ]
