# Generated by Django 5.0.2 on 2024-03-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_alter_choice_question_remove_progress_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"verbose_name": "Choice", "verbose_name_plural": "Choices"},
        ),
        migrations.RemoveField(
            model_name="choice",
            name="is_correct",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="text",
        ),
        migrations.AddField(
            model_name="choice",
            name="choice",
            field=models.CharField(
                default=1,
                help_text="Enter the choice text that you want displayed",
                max_length=1000,
                verbose_name="Content",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="choice",
            name="correct",
            field=models.BooleanField(
                default=False,
                help_text="Is this a correct answer?",
                verbose_name="Correct",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="choice_order",
            field=models.CharField(
                blank=True,
                choices=[
                    ("content", "Content"),
                    ("random", "Random"),
                    ("none", "None"),
                ],
                help_text="The order in which multichoice choice options are displayed to the user",
                max_length=30,
                null=True,
                verbose_name="Choice Order",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="answers_at_end",
            field=models.BooleanField(
                default=False,
                help_text="Correct answer is NOT shown after question. Answers displayed at the end.",
                verbose_name="Answers at end",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="exam_paper",
            field=models.BooleanField(
                default=False,
                help_text="If yes, the result of each attempt by a user will be stored. Necessary for marking.",
                verbose_name="Exam Paper",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="random_order",
            field=models.BooleanField(
                default=False,
                help_text="Display the questions in a random order or as they are set?",
                verbose_name="Random Order",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="single_attempt",
            field=models.BooleanField(
                default=False,
                help_text="If yes, only one attempt by a user will be permitted.",
                verbose_name="Single Attempt",
            ),
        ),
    ]
