# Generated by Django 5.0.2 on 2024-03-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_alter_choice_options_remove_choice_is_correct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="choice",
            field=models.CharField(
                default=False,
                help_text="Enter the choice text that you want displayed",
                max_length=1000,
                verbose_name="Content",
            ),
        ),
    ]
