# Generated by Django 5.0.2 on 2024-03-15 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_alter_choice_choice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Question", "verbose_name_plural": "Questions"},
        ),
        migrations.RemoveField(
            model_name="question",
            name="choice_order",
        ),
        migrations.RemoveField(
            model_name="question",
            name="mark",
        ),
        migrations.RemoveField(
            model_name="question",
            name="text",
        ),
        migrations.AddField(
            model_name="question",
            name="content",
            field=models.CharField(
                default="default",
                help_text="Enter the question text that you want displayed",
                max_length=1000,
                verbose_name="Question",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="Explanation to be shown after the question has been answered.",
                max_length=2000,
                verbose_name="Explanation",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="figure",
            field=models.ImageField(
                blank=True,
                help_text="Add an image for the question if it's necessary.",
                null=True,
                upload_to="uploads/%Y/%m/%d",
                verbose_name="Figure",
            ),
        ),
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.CreateModel(
            name="MCQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=1000, verbose_name="Question")),
                ("mark", models.IntegerField(default=1, verbose_name="Mark")),
                (
                    "choice_order",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("content", "Content"),
                            ("random", "Random"),
                            ("none", "None"),
                        ],
                        help_text="The order in which multichoice choice options are displayed to the user",
                        max_length=30,
                        null=True,
                        verbose_name="Choice Order",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.quiz",
                        verbose_name="Quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multiple Choice Question",
                "verbose_name_plural": "Multiple Choice Questions",
            },
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.mcquestion",
                verbose_name="Question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ManyToManyField(
                blank=True, to="quiz.quiz", verbose_name="Quiz"
            ),
        ),
    ]
