# Generated by Django 5.0.2 on 2024-03-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_alter_question_options_remove_question_choice_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200, null=True)),
                ("op1", models.CharField(max_length=200, null=True)),
                ("op2", models.CharField(max_length=200, null=True)),
                ("op3", models.CharField(max_length=200, null=True)),
                ("op4", models.CharField(max_length=200, null=True)),
                ("ans", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="mcquestion",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="course",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="module",
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="MCQuestion",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
    ]
