# Generated by Django 5.0.2 on 2024-03-21 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0016_course_image"),
        ("quiz", "0010_quesmodel_remove_mcquestion_quiz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quesmodel",
            name="module",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.module",
            ),
        ),
    ]
