# Generated by Django 5.0.2 on 2024-03-21 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0016_course_image"),
        ("quiz", "0012_quesmodel_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quesmodel",
            name="course",
        ),
        migrations.RemoveField(
            model_name="quesmodel",
            name="module",
        ),
        migrations.AlterField(
            model_name="quesmodel",
            name="ans",
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name="quesmodel",
            name="op1",
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name="quesmodel",
            name="op2",
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name="quesmodel",
            name="op3",
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name="quesmodel",
            name="op4",
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name="quesmodel",
            name="question",
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("total_score", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.module",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quesmodel",
            name="quiz",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
            ),
        ),
    ]
