# Generated by Django 5.0.2 on 2024-03-28 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_alter_module_unique_together"),
        ("quiz", "0014_question_choice_quizattempt_delete_quesmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizattempt",
            old_name="student",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice_text",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="is_correct",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_text",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="course",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="total_questions",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="total_score",
        ),
        migrations.AddField(
            model_name="choice",
            name="text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="text",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="module",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="courses.module"
            ),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
            ),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
