# Generated by Django 5.0.2 on 2024-04-04 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0016_alter_choice_question_alter_question_quiz_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizattempt",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="quizattempt",
            name="user",
        ),
        migrations.RemoveField(
            model_name="question",
            name="correct_answer",
        ),
        migrations.RemoveField(
            model_name="question",
            name="text",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="module",
        ),
        migrations.AddField(
            model_name="question",
            name="content",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="desc",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="number_of_questions",
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="time",
            field=models.IntegerField(
                default=1, help_text="Duration of the quiz in seconds", null=True
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200, null=True)),
                ("correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marks_Of_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="QuizAttempt",
        ),
    ]
