# Generated by Django 5.0.2 on 2024-04-04 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_delete_activitylog_chapter_slug_chapter_summary_and_more"),
        ("quiz", "0020_quiz_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="Module",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.module",
            ),
        ),
    ]
