# Generated by Django 5.0.2 on 2024-04-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_course_total_quiz_score_module_quiz_score"),
        ("quiz", "0022_rename_answer_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="marks_of_user",
            name="module",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.module",
            ),
        ),
    ]
