# Generated by Django 5.0.2 on 2024-02-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={"verbose_name_plural": "Module"},
        ),
        migrations.RenameField(
            model_name="course",
            old_name="text",
            new_name="Title",
        ),
        migrations.AddField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
