# Generated by Django 5.0.2 on 2024-02-29 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_module_options_rename_text_course_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="module_no",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="module",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_number", models.IntegerField()),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.module"
                    ),
                ),
            ],
        ),
    ]
