# Generated by Django 5.0.2 on 2024-02-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_module_module_no_module_progress_chapter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="module",
            old_name="topic",
            new_name="Course",
        ),
    ]
