# Generated by Django 5.0.2 on 2024-02-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_module_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="module",
            old_name="text",
            new_name="title",
        ),
    ]
