# Generated by Django 5.0.2 on 2024-02-29 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_rename_text_module_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="Title",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="module",
            old_name="Course",
            new_name="course",
        ),
        migrations.RemoveField(
            model_name="upload",
            name="Module",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="course",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="slug",
        ),
        migrations.AddField(
            model_name="upload",
            name="chapter",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.chapter",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="chapter",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.chapter",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chapter",
            name="chapter_number",
            field=models.IntegerField(default=0),
        ),
    ]
