# Generated by Django 5.0.2 on 2024-03-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_uploadvideo_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="title",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
