# Generated by Django 5.0.2 on 2024-03-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_chapter_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
