# Generated by Django 5.0.2 on 2024-03-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_remove_course_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="owner",
        ),
    ]
