# Generated by Django 5.0.2 on 2024-03-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_remove_course_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="code",
        ),
    ]
