# Generated by Django 5.0.2 on 2024-03-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_remove_course_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
