# Generated by Django 5.0.2 on 2024-03-28 07:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_alter_module_unique_together"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActivityLog",
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="summary",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="upload",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.chapter"
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.FileField(
                help_text="Valid Files: pdf, docx, doc, xls, xlsx, ppt, pptx, zip, rar, 7zip",
                upload_to="chapter_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "docx",
                            "doc",
                            "xls",
                            "xlsx",
                            "ppt",
                            "pptx",
                            "zip",
                            "rar",
                            "7zip",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="uploadvideo",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.chapter"
            ),
        ),
        migrations.AlterField(
            model_name="uploadvideo",
            name="video",
            field=models.FileField(
                help_text="Valid video formats: mp4, mkv, wmv, 3gp, f4v, avi, mp3",
                upload_to="chapter_videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp4", "mkv", "wmv", "3gp", "f4v", "avi", "mp3"]
                    )
                ],
            ),
        ),
    ]
