# Generated by Django 5.0.2 on 2024-04-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_delete_activitylog_chapter_slug_chapter_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="total_quiz_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="module",
            name="quiz_score",
            field=models.FloatField(default=0),
        ),
    ]
